GET http://152.70.175.53/api/consumation/findAll

####

POST http://localhost:8080/api/consumation/create
Content-Type: application/json

{
  "person":{
    "firstName": "Rosi",
    "lastName": "Dosi",
    "yearno": 2020,
    "className": "1c"
  },
  "date": "2020-06-06",
  "hasConsumed" : "true"
}


####

GET http://localhost:8080/api/person

####
POST http://localhost:8080/api/person
Content-Type: application/json

{
  "firstName": "Rosi",
  "lastName": "Dosi",
  "yearno": 2020,
  "className": "1c"
}


###

GET http://152.70.175.53/api/person/findById/3

####

POST http://localhost:8080/api/nfccard/assign-card/345
Content-Type: application/json

####

POST http://152.70.175.53/api/nfccard/assign-card/234/3
Content-Type: application/json

####

POST http://localhost:8080/api/nfccard/assign-card/123/2
Content-Type: application/json

###

GET http://localhost:8080/api/nfccard/nfcid/123
Content-Type: application/json

###

GET http://localhost:8080/api/person/importPersons

###

GET http://localhost:8080/api/consumation/importConsumations


###

GET  http://152.70.175.53/api/nfcCard/findByNfcId/5


###

